{
 "title": "Strom",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "MyStromSwitch",
    "query": "SELECT name\nFROM switch\nORDER BY sort"
   }
  ]
 },
 "panels": [
  {
   "title": "Selection Watt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "queryText": "SELECT\n    sd.ws as Watt,\n    sd.created as ts\nFROM switch_data as sd INNER JOIN\n    switch as s ON\n        sd.switch_id = s.id\nWHERE s.name = 'Balkon Solar' AND\n    sd.created BETWEEN 1743733865 AND 1743820265",
     "rawQueryText": "SELECT\n    sd.ws as Watt,\n    sd.created as ts\nFROM switch_data as sd INNER JOIN\n    switch as s ON\n        sd.switch_id = s.id\nWHERE s.name = '$MyStromSwitch' AND\n    sd.created BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Selection Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "SELECT\n    sd.temperature as Temperature,\n    sd.created as ts\nFROM switch_data as sd INNER JOIN\n    switch as s ON\n        sd.switch_id = s.id\nWHERE s.name = 'Balkon Solar' AND\n    sd.created BETWEEN 1743733865 AND 1743820265",
     "rawQueryText": "SELECT\n    sd.temperature as Temperature,\n    sd.created as ts\nFROM switch_data as sd INNER JOIN\n    switch as s ON\n        sd.switch_id = s.id\nWHERE s.name = '$MyStromSwitch' AND\n    sd.created BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Current Selection Production",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "queryText": "WITH current_power AS (\n    SELECT\n        sd.ws,\n        MAX(sd.created)\n    FROM switch_data AS sd INNER JOIN\n         switch AS s ON\n             sd.switch_id = s.id\n    WHERE s.name = 'Balkon Solar' AND\n        s.is_input = 1 AND\n        sd.created BETWEEN 1743734310 AND 1743820710\n    GROUP BY s.id\n    ORDER BY sd.created DESC\n)\nSELECT\n    COALESCE(SUM(cp.ws), 0) as Power\nFROM current_power AS cp",
     "rawQueryText": "WITH current_power AS (\n    SELECT\n        sd.ws,\n        MAX(sd.created)\n    FROM switch_data AS sd INNER JOIN\n         switch AS s ON\n             sd.switch_id = s.id\n    WHERE s.name = '$MyStromSwitch' AND\n        s.is_input = 1 AND\n        sd.created BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\n    GROUP BY s.id\n    ORDER BY sd.created DESC\n)\nSELECT\n    COALESCE(SUM(cp.ws), 0) as Power\nFROM current_power AS cp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Current Selection Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "queryText": "WITH current_power AS (\n    SELECT\n        sd.ws,\n        MAX(sd.created)\n    FROM switch_data AS sd INNER JOIN\n         switch AS s ON\n             sd.switch_id = s.id\n    WHERE s.name = 'Balkon Solar' AND\n        s.is_input = 0 AND\n        sd.created BETWEEN 1744867639 AND 1744954039\n    GROUP BY s.id\n    ORDER BY sd.created DESC\n)\nSELECT\n    COALESCE(SUM(cp.ws), 0) as Power\nFROM current_power AS cp",
     "rawQueryText": "WITH current_power AS (\n    SELECT\n        sd.ws,\n        MAX(sd.created)\n    FROM switch_data AS sd INNER JOIN\n         switch AS s ON\n             sd.switch_id = s.id\n    WHERE s.name = '$MyStromSwitch' AND\n        s.is_input = 0 AND\n        sd.created BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\n    GROUP BY s.id\n    ORDER BY sd.created DESC\n)\nSELECT\n    COALESCE(SUM(cp.ws), 0) as Power\nFROM current_power AS cp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "All Consume / Production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "queryText": "SELECT\n    sd.ws as Production,\n    sd.created as ts\nFROM switch_data as sd INNER JOIN\n    switch as s ON\n        sd.switch_id = s.id\nWHERE s.is_input = 1 AND\n    sd.created BETWEEN 1743733865 AND 1743820265",
     "rawQueryText": "SELECT\n    sd.ws as Production,\n    sd.created as ts\nFROM switch_data as sd INNER JOIN\n    switch as s ON\n        sd.switch_id = s.id\nWHERE s.is_input = 1 AND\n    sd.created BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT\n    SUM(sd.ws) as Consume,\n    sd.created as ts\nFROM switch_data as sd INNER JOIN\n    switch as s ON\n        sd.switch_id = s.id\nWHERE s.is_input = 0 AND\n    sd.created BETWEEN 1743733865 AND 1743820265\nGROUP BY sd.created",
     "rawQueryText": "SELECT\n    SUM(sd.ws) as Consume,\n    sd.created as ts\nFROM switch_data as sd INNER JOIN\n    switch as s ON\n        sd.switch_id = s.id\nWHERE s.is_input = 0 AND\n    sd.created BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY sd.created",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Current ∑ Production",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "queryText": "WITH current_power AS (\n    SELECT\n        sd.ws,\n        MAX(sd.created)\n    FROM switch_data AS sd INNER JOIN\n         switch AS s ON\n             sd.switch_id = s.id\n    WHERE s.is_input = 1 AND\n        sd.created >= UNIXEPOCH() - 3600\n    GROUP BY s.id\n    ORDER BY sd.created DESC\n)\nSELECT\n    SUM(cp.ws) as Power\nFROM current_power AS cp",
     "rawQueryText": "WITH current_power AS (\n    SELECT\n        sd.ws,\n        MAX(sd.created)\n    FROM switch_data AS sd INNER JOIN\n         switch AS s ON\n             sd.switch_id = s.id\n    WHERE s.is_input = 1 AND\n        sd.created >= UNIXEPOCH() - 3600\n    GROUP BY s.id\n    ORDER BY sd.created DESC\n)\nSELECT\n    SUM(cp.ws) as Power\nFROM current_power AS cp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Current ∑ Consumption",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "queryText": "WITH current_power AS (\n    SELECT\n        sd.ws,\n        MAX(sd.created)\n    FROM switch_data AS sd INNER JOIN\n         switch AS s ON\n             sd.switch_id = s.id\n    WHERE s.is_input = 0 AND\n        sd.created >= UNIXEPOCH() - 3600\n    GROUP BY s.id\n    ORDER BY sd.created DESC\n)\nSELECT\n    SUM(cp.ws) as Power\nFROM current_power AS cp",
     "rawQueryText": "WITH current_power AS (\n    SELECT\n        sd.ws,\n        MAX(sd.created)\n    FROM switch_data AS sd INNER JOIN\n         switch AS s ON\n             sd.switch_id = s.id\n    WHERE s.is_input = 0 AND\n        sd.created >= UNIXEPOCH() - 3600\n    GROUP BY s.id\n    ORDER BY sd.created DESC\n)\nSELECT\n    SUM(cp.ws) as Power\nFROM current_power AS cp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Latest production time",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "queryText": "SELECT\n    strftime('%Y-%m-%d %H:%M:%S', sd.created, 'unixepoch')\nFROM switch_data AS sd INNER JOIN\n      switch AS s ON\n        sd.switch_id = s.id\nWHERE s.is_input = 1 AND\n    sd.ws > 0\nORDER BY sd.created DESC\nLIMIT 1",
     "rawQueryText": "SELECT\n    strftime('%Y-%m-%d %H:%M:%S', sd.created, 'unixepoch')\nFROM switch_data AS sd INNER JOIN\n      switch AS s ON\n        sd.switch_id = s.id\nWHERE s.is_input = 1 AND\n    sd.ws > 0\nORDER BY sd.created DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Timerange ∑ Production",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "queryText": "WITH power_usage AS (\n    SELECT\n        sd.ws,\n        sd.created,\n        LEAD(sd.created) OVER (PARTITION by sd.switch_id ORDER BY sd.created) as next_created\n    FROM switch_data AS sd INNER JOIN\n        switch AS s ON\n            sd.switch_id = s.id\n    WHERE s.is_input = 1 AND\n        created BETWEEN 1743733865 AND 1743820265\n)\nSELECT\n    SUM(ws * (next_created - created) / 3600) AS total_wh\nFROM\n    power_usage\nWHERE\n    next_created IS NOT NULL\n    ",
     "rawQueryText": "WITH power_usage AS (\n    SELECT\n        sd.ws,\n        sd.created,\n        LEAD(sd.created) OVER (PARTITION by sd.switch_id ORDER BY sd.created) as next_created\n    FROM switch_data AS sd INNER JOIN\n        switch AS s ON\n            sd.switch_id = s.id\n    WHERE s.is_input = 1 AND\n        created BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\n)\nSELECT\n    SUM(ws * (next_created - created) / 3600) AS total_wh\nFROM\n    power_usage\nWHERE\n    next_created IS NOT NULL\n    ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Timerange ∑ Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "queryText": "WITH power_usage AS (\n    SELECT\n        sd.ws,\n        sd.created,\n        LEAD(sd.created) OVER (PARTITION by sd.switch_id ORDER BY sd.created) as next_created\n    FROM switch_data AS sd INNER JOIN\n        switch AS s ON\n            sd.switch_id = s.id\n    WHERE s.is_input = 0 AND\n        created BETWEEN 1744867639 AND 1744954039\n)\nSELECT\n    SUM(ws * (next_created - created) / 3600) AS total_wh\nFROM\n    power_usage\nWHERE\n    next_created IS NOT NULL\n    ",
     "rawQueryText": "WITH power_usage AS (\n    SELECT\n        sd.ws,\n        sd.created,\n        LEAD(sd.created) OVER (PARTITION by sd.switch_id ORDER BY sd.created) as next_created\n    FROM switch_data AS sd INNER JOIN\n        switch AS s ON\n            sd.switch_id = s.id\n    WHERE s.is_input = 0 AND\n        created BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\n)\nSELECT\n    SUM(ws * (next_created - created) / 3600) AS total_wh\nFROM\n    power_usage\nWHERE\n    next_created IS NOT NULL\n    ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "No production since",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "targets": [
    {
     "queryText": "WITH diff AS (\n    SELECT \n        unixepoch() - sd.created AS seconds_diff\n    FROM switch_data AS sd INNER JOIN\n      switch AS s ON\n        sd.switch_id = s.id\n    WHERE s.is_input = 1 AND\n        sd.ws > 0\n    ORDER BY sd.created DESC\n    LIMIT 1\n)\nSELECT\n    (seconds_diff / 86400) || ' days, ' ||\n    ((seconds_diff % 86400) / 3600) || ' hours, ' ||\n    ((seconds_diff % 3600) / 60) || ' minutes' AS time_diff\nFROM diff;",
     "rawQueryText": "WITH diff AS (\n    SELECT \n        unixepoch() - sd.created AS seconds_diff\n    FROM switch_data AS sd INNER JOIN\n      switch AS s ON\n        sd.switch_id = s.id\n    WHERE s.is_input = 1 AND\n        sd.ws > 0\n    ORDER BY sd.created DESC\n    LIMIT 1\n)\nSELECT\n    (seconds_diff / 86400) || ' days, ' ||\n    ((seconds_diff % 86400) / 3600) || ' hours, ' ||\n    ((seconds_diff % 3600) / 60) || ' minutes' AS time_diff\nFROM diff;"
    }
   ]
  }
 ]
}